


# Generated by Django 3.0 on 2021-11-26 12:48
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('Outils', '0001_initial'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='role',
            name='eval',
        ),
        migrations.AddField(
            model_name='role',
            name='eval',
            field=models.ManyToManyField(related_name='roles', through='Outils.EvalRoles', to='Outils.Evaluation'),
),
        
    ]
